export {default as Navbar} from "./Navbar"
export {default as Registration} from "./Registration"
export {default as Login} from "./Login"
export {default as Input} from "./Input"
export {default as Home} from "./Home"
export {default as NoPage} from "./NoPage"
